name: CreativeZone
version: 1.0.0
main: dev.madtechs.creativeZone.CreativeZone
description: A plugin that allows players to make separate worlds that are in creative mode
author: PaperMC
website: https://github.com/MADMAN-Modding/CreativeZones
api-version: '1.21.11'

commands:
  createZone:
    description: Make a new zone with X chunks in each direction (squares)
    usage: /<command> <chunks>
  pullChunks:
    description: Pull chunks from the overworld
    usage: /<command> <chunks>
  goToOverworld:
    description: Go back to the overworld
    usage: /<command>
  goToZone:
    description: Go to your zone
    usage: /<command> [player]
  deleteZone:
    description: Delete your zone
    Usage: /<command> [player]
  allowPlayer:
    description: Allow a player in your zone
    Usage: /<command> <playerName>
  listAllowedPlayers:
    description: List of the allowed players